// ============================================================================
// Task Controller
// ============================================================================
// PURPOSE:
// This controller handles all HTTP requests related to tasks (GET, POST, PUT, DELETE).
// It acts as the "router" between the frontend (REST client) and the backend database.
// Each method handles a specific endpoint and delegates work to the TaskRepository.
//
// KEY CONCEPTS:
//
// 1. @RESTCONTROLLER: Tells Spring this class handles HTTP requests and returns JSON.
//    - Every method returns JSON instead of HTML
//    - Without this annotation, Spring would treat it as a traditional web controller
//
// 2. @REQUESTMAPPING("/api/tasks"): Sets the base URL for all methods in this class.
//    - This controller handles all URLs starting with /api/tasks
//    - /api/tasks/count, /api/tasks/all, /api/tasks/1 etc. go through here
//    - Think of it like "mounting" this controller at a base path
//
// 3. @AUTOWIRED (Dependency Injection): Tells Spring "give me a TaskRepository."
//    - Spring automatically creates and injects a TaskRepository instance
//    - You don't call `new TaskRepository()` manually
//    - This follows the "Inversion of Control" (IoC) pattern
//    - In frontend terms: like requesting a service from a provider, not creating it yourself
//
// 4. @GETMAPPING("/count"): Handles GET requests to /api/tasks/count.
//    - The full URL becomes: http://localhost:8080/api/tasks/count
//    - Similar annotations: @PostMapping, @PutMapping, @DeleteMapping
//
// 5. HTTP METHODS:
//    - GET    = retrieve data (read-only, safe)
//    - POST   = create new data
//    - PUT    = update existing data
//    - DELETE = remove data
//
// 6. RETURN TYPES:
//    - Spring automatically converts return values to JSON
//    - `long` becomes JSON number: 0, 5, 10, etc.
//    - Objects become JSON objects with fields as properties
//
// FRONTEND ENGINEER NOTE:
// A controller is basically an API endpoint handler. You define HTTP routes
// and what code runs when someone calls that route. It's like defining
// Express.js routes in Node.js or Next.js API routes.
// ============================================================================

package com.example.taskboard.controller;

import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.beans.factory.annotation.Autowired;
import com.example.taskboard.repository.TaskRepository;

// @RestController: Marks this as an HTTP request handler. All methods return JSON.
@RestController
// @RequestMapping: Base URL path for all methods in this class. /api/tasks/count, /api/tasks/all, etc.
@RequestMapping("/api/tasks")
public class TaskController {

    // @Autowired: Spring dependency injection. Automatically provides a TaskRepository instance.
    // Instead of: TaskRepository taskRepository = new TaskRepository()
    // Spring manages the lifecycle and wires it in for you.
    @Autowired
    private TaskRepository taskRepository;

    // @GetMapping: Handle HTTP GET requests to /api/tasks/count
    // Returns the total number of tasks in the database as a JSON number.
    // Example response: curl http://localhost:8080/api/tasks/count → 0
    @GetMapping("/count")
    public long getTaskCount() {
        // taskRepository.count() is auto-generated by Spring Data JPA.
        // It runs: SELECT COUNT(*) FROM task
        return taskRepository.count();
    }

}