spring.application.name=taskboard
# Use H2 in-memory - perfect for initial prep and testing
spring.datasource.url=jdbc:postgresql://192.168.78.221:5432/taskboard
spring.datasource.username=taskuser
spring.datasource.password=taskpassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Explicitly set the dialect to prevent the "Unable to determine Dialect" error
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=update

# Enable the console so you can verify the DB at http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=true

# Actuator
management.endpoints.web.exposure.include=health
management.endpoints.web.cors.allowed-origins=http://localhost:5173
management.endpoints.web.cors.allow-credentials=true